import { Link } from "react-router-dom";
import { LogoMark } from "@/components/LogoMark";

const paragraphs = [
  "Dedicated hands of delegates skimming through pages of research, rushed voices defending their stance, and a room full of jittery delegates deciding their next move. When the world is on fire, what can a mere committee of 30 students do? This is the question we ask while conducting the TESMUN 2026. Model United Nations is a long running tradition in The Excelsior School, spanning decades, and it has commenced once again with delegates more eager than ever.",
  "TESMUN is designed to teach students about diplomacy, politics, and global problems. It has stood to provide young minds with new ideas, broaden their perspectives, and sharpen their skills. Their confidence rises along with their hands, raising the placards high, giving pretend solutions to real-life problems, while the dais panel hurries to calm them. Blending pretend with reality, the MUN equips students with skills, ready to step into the real world.",
  "The earth, labelled the blue planet, is now scorched red with fires of humanity's own making. Flames spread around the world, from the trenches of Ukraine to the bombed streets of Gaza, from the tensions of the Strait of Hormuz to missiles lighting up the sky. Even amid the silence held for the lost lives, the wilderness still calls for help. The melting glaciers, rivers running dry, air thickening with pollution, and forests disappearing to feed industries. These are not distant catastrophes, they are knocking at our doorstep.",
  "With the flames around the world expanding, the young minds of this generation are handed the responsibility to extinguish them. Following this, The Excelsior School has taken initiative to prepare young minds before the real crisis strikes. The model united nations is a simulation that puts delegates on the spot. It is an event run completely by students, assuming the roles of Secretary-General, dias panel, and delegates, or as reporters, camera operators, editors, and logistics managers working behind the scenes to make it possible.",
  "As in preceding years, TESMUN 2026 has seven committees, including four international and three national committees. The eight graders are handed over the responsibilities of our federal parliament, assuming roles of politicians, while ninth graders handle the international committees in the United Nations including UNHRC, UNEP, ECOSOC, and DISEC. Every delegate arrives unsure about procedure but leaves well-versed in the workings of MUN.",
  "Though student delegates remain the heart of the event, seventh and tenth graders form the backbone that keeps it running, from Press to IT to Logistics. Seventh graders take their first steps into the world of MUN, assisting their seniors and laying the groundwork for the roles they'll grow into next year, while tenth graders lead the event as a whole.",
  "TESMUN cannot extinguish the fires of Ukraine, Gaza, or Hormuz. No simulation could. What it offers instead is long lasting skills: the confidence to take the stage under a spotlight, the discipline to turn scattered points into a practical answer, and a glimpse of what it truly means to carry a country's, or a politician's, responsibility. Clause by clause, compromise by compromise, each resolution is a building block for a change in the delegate's life.",
  "Lastly, the editorial team would like to appreciate each and every hand that worked to put TESMUN 2026 together. The wonderful photos, new articles, videos, and interviews have made this MUN complete. Thank you to everyone whose capable hands have helped run this event.",
  "The world is on fire. This generation did not light the match. But within these walls, they prove, placard by placard, resolution by resolution, that they are prepared to carry the extinguisher forward.",
];

export default function Editorial() {
  return <main className="min-h-screen bg-[#f5f3ee] px-6 py-16 text-[#172331] sm:px-10 md:py-24"><article className="mx-auto max-w-4xl"><Link to="/press" className="text-[10px] uppercase tracking-[0.2em] text-[#6d7780] hover:text-[#172331]">← Press desk</Link><header className="flex flex-col items-center text-center"><LogoMark size={54} className="mt-10" /><div className="mt-7 w-20 border-t border-[#172331]/35" /><p className="mt-6 text-[11px] font-semibold uppercase tracking-[0.38em]">Editorial</p><div className="mt-6 w-20 border-t border-[#172331]/35" /><h1 className="mt-10 max-w-3xl font-display text-balance text-4xl font-bold leading-[1.05] sm:text-6xl">A World on Fire, A Generation Handed the Extinguisher</h1></header><div className="mx-auto mt-12 max-w-2xl border-t border-[#172331]/20 pt-10">{paragraphs.map((paragraph) => <p key={paragraph} className="mb-7 text-[15px] leading-8 text-[#394650]">{paragraph}</p>)}</div></article></main>;
}
