import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { newsArchive, sessionLabel, dayLabel, archiveArticleCount, type ArchiveArticle } from "@/lib/news-archive";

function Reveal({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  return <motion.div initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: 0.75, delay }}>{children}</motion.div>;
}
function Story({ article, index }: { article: ArchiveArticle; index: number }) {
  return <Reveal delay={index * 0.035}><article className="group border-b border-ink/25 py-7 first:pt-0 md:py-8"><div className="grid gap-7 md:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] md:items-center md:gap-12"><div className="order-2 md:order-1"><div className="flex items-center gap-3 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-ink/55"><img src={article.committeeLogo} alt="" className="size-8 object-contain" /><span>{article.committee}</span><span>·</span><span>{article.date}</span></div><p className="mt-2 font-mono text-[10px] uppercase tracking-[0.16em] text-ink/45">By {article.author}</p><h3 className="mt-5 font-display text-3xl uppercase leading-[0.95] tracking-[-0.035em] text-ink sm:text-4xl">{article.headline}</h3><p className="mt-5 max-w-xl font-serif text-lg leading-7 text-ink/68">{article.summary}</p><Link to={`/news/${article.session}/${article.day}/${article.committeeSlug}`} className="mt-6 inline-block font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-ink underline">Read dispatch</Link></div><motion.figure className="order-1 overflow-hidden bg-ink md:order-2"><img src={article.image} alt={article.imageAlt} className="block aspect-[16/10] w-full object-cover transition duration-1000 group-hover:scale-[1.035]" /></motion.figure></div></article></Reveal>;
}
export default function Newspaper() {
  return <main className="paper-grain min-h-screen bg-[#f5f0e7] text-ink"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-8 md:px-12 md:py-14"><header className="border-b-2 border-ink pb-8"><div className="flex items-center justify-between font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-ink/55"><Link to="/press">← Press</Link><span>TESMUN XIV · Kathmandu</span></div><div className="mt-6 border-y-[7px] border-ink bg-ink px-4 py-7 text-center sm:px-8 sm:py-10"><p className="font-mono text-[10px] uppercase tracking-[0.4em] text-[#f5f0e7]/65">International Press Corps</p><h1 className="mt-4 font-display text-6xl font-semibold uppercase leading-[0.8] tracking-[-0.085em] text-[#f5f0e7] sm:text-8xl md:text-[9.5rem]">THE TESMUN TIMES</h1><p className="mt-5 border-t border-[#f5f0e7]/30 pt-4 font-mono text-[10px] uppercase tracking-[0.26em] text-[#f5f0e7]/65">A continuous record of debate, diplomacy and the day · {archiveArticleCount} dispatches</p></div></header><nav aria-label="Jump to session" className="flex flex-wrap justify-center gap-3 py-8"><a href="#final-session" className="border border-ink/50 px-4 py-2 font-mono text-[10px] font-bold uppercase tracking-[0.16em] hover:bg-ink hover:text-[#f5f0e7]">Final Session</a><a href="#second-session" className="border border-ink/50 px-4 py-2 font-mono text-[10px] font-bold uppercase tracking-[0.16em] hover:bg-ink hover:text-[#f5f0e7]">Second Session</a><a href="#first-session" className="border border-ink/50 px-4 py-2 font-mono text-[10px] font-bold uppercase tracking-[0.16em] hover:bg-ink hover:text-[#f5f0e7]">First Session</a></nav><div className="mx-auto max-w-5xl">{newsArchive.map((day) => <section id={day.session === 3 && day.day === 3 ? "final-session" : day.session === 2 && day.day === 2 ? "second-session" : day.session === 1 && day.day === 2 ? "first-session" : undefined} key={`${day.session}-${day.day}`} className="scroll-mt-8 pt-16 md:pt-24"><Reveal><div className="border-y-2 border-ink py-8 md:py-12"><p className="font-mono text-[11px] font-bold uppercase tracking-[0.28em] text-ink/55">{sessionLabel[day.session]}</p><h2 className="relative mt-3 font-display text-6xl uppercase leading-[0.82] tracking-[-0.07em] text-ink sm:text-8xl">{dayLabel(day.day)}</h2><div className="mt-7 h-px bg-ink/60" /></div></Reveal>{day.articles.map((article, index) => <Story key={article.committeeSlug} article={article} index={index} />)}</section>)}</div></div></main>;
}
