import { Link, useParams } from "react-router-dom";
import { newsArchive, sessionLabel, dayLabel } from "@/lib/news-archive";

export default function NewsDispatch() {
  const { session, day, article } = useParams();
  const sessionNumber = Number(session);
  const dayNumber = Number(day);
  const currentDay = newsArchive.find((entry) => entry.session === sessionNumber && entry.day === dayNumber);
  const story = currentDay?.articles.find((entry) => entry.committeeSlug === article);
  if (!currentDay || !story) return <main className="min-h-screen bg-[#f5f0e7] px-6 py-24 text-ink"><h1 className="font-display text-6xl uppercase">Dispatch not found</h1><Link className="mt-8 inline-block underline" to="/news">Return to the archive</Link></main>;
  const index = currentDay.articles.findIndex((entry) => entry.committeeSlug === article);
  const previous = currentDay.articles[index - 1];
  const next = currentDay.articles[index + 1];
  return <main className="paper-grain min-h-screen bg-[#f5f0e7] text-ink"><div className="mx-auto max-w-6xl px-5 py-8 sm:px-10 md:py-14"><header className="flex items-center justify-between border-b-2 border-ink pb-6 font-mono text-[10px] font-bold uppercase tracking-[0.18em]"><Link to="/news">← The TESMUN Times</Link><span>{sessionLabel[sessionNumber as 1 | 2 | 3]} · {dayLabel(dayNumber as 1 | 2 | 3)}</span></header><article className="mx-auto max-w-6xl py-10 md:py-16"><div className="flex items-center gap-3 font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-ink/55"><img src={story.committeeLogo} alt="" className="size-9 object-contain" />{story.committee} · {story.date}</div><h1 className="mt-7 max-w-5xl font-display text-4xl uppercase leading-[0.9] tracking-[-0.05em] sm:text-5xl md:text-[5.25rem]">{story.headline}</h1><p className="mt-8 max-w-2xl font-serif text-xl leading-8 text-ink/70">{story.summary}</p><figure className="mt-12 overflow-hidden bg-ink"><img src={story.image} alt={story.imageAlt} className="aspect-[16/9] w-full object-cover saturate-125 contrast-105" /></figure><div className="mt-12 grid gap-10 border-t border-ink/25 pt-8 md:grid-cols-2"><div className="font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-ink/50"><p>Filed from the floor</p><p className="mt-4 normal-case tracking-normal text-ink/70">By {story.author || ""}</p></div><div className="font-serif text-lg leading-8 text-ink/80 md:columns-2 md:gap-8">{story.body.map((paragraph) => <p key={paragraph} className="mb-6 last:mb-0">{paragraph}</p>)}</div></div></article><nav className="grid gap-5 border-t-2 border-ink pt-7 sm:grid-cols-2">{previous ? <Link to={`/news/${session}/${day}/${previous.committeeSlug}`} className="border border-ink/20 p-5 hover:bg-ink hover:text-[#f5f0e7]"><span className="font-mono text-[10px] uppercase tracking-[0.2em]">Previous dispatch</span><strong className="mt-3 block font-display text-2xl uppercase">{previous.committee}</strong></Link> : <span />}{next ? <Link to={`/news/${session}/${day}/${next.committeeSlug}`} className="border border-ink/20 p-5 text-right hover:bg-ink hover:text-[#f5f0e7]"><span className="font-mono text-[10px] uppercase tracking-[0.2em]">Next dispatch</span><strong className="mt-3 block font-display text-2xl uppercase">{next.committee}</strong></Link> : <span />}</nav></div></main>;
}
