import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { newsArchive, sessionLabel, dayLabel, archiveArticleCount, type ArchiveArticle } from "@/lib/news-archive";

function Reveal({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  return <motion.div initial={{ opacity: 0, y: 28, filter: "blur(8px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: 0.75, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>;
}

function Story({ article, index }: { article: ArchiveArticle; index: number }) {
  return <Reveal delay={index * 0.035}><article className="group border-b border-ink/25 py-12 first:pt-0 md:py-16"><div className="grid gap-7 md:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] md:items-center md:gap-12"><div className="order-2 md:order-1"><div className="flex items-center gap-3 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-ink/55"><img src={article.committeeLogo} alt="" className="size-8 object-contain" /><span>{article.committee}</span><span className="text-ink/30">·</span><span>{article.date}</span></div><h3 className="mt-5 font-display text-4xl uppercase leading-[0.9] tracking-[-0.045em] text-ink sm:text-5xl">{article.headline}</h3><p className="mt-5 max-w-xl font-serif text-lg leading-7 text-ink/68">{article.summary}</p><Link to={`/news/${article.session}/${article.day}/${article.committeeSlug}`} className="mt-6 inline-block font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-ink underline decoration-ink/30 underline-offset-4 transition hover:decoration-gold">Read dispatch</Link></div><motion.figure className="order-1 overflow-hidden bg-ink md:order-2" initial={{ y: 18 }} whileInView={{ y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: 1, ease: "easeOut" }}><img src={article.image} alt={article.imageAlt} className="aspect-[16/10] w-full object-cover grayscale contrast-[1.05] transition duration-1000 group-hover:scale-[1.035] group-hover:grayscale-[0.35]" /></motion.figure></div></article></Reveal>;
}

export default function Newspaper() {
  return <main className="paper-grain min-h-screen bg-[#f5f0e7] text-ink"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-8 md:px-12 md:py-14"><header className="border-b-2 border-ink pb-8"><div className="flex items-center justify-between font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-ink/55"><Link to="/press" className="hover:text-ink">← Press</Link><span>TESMUN XIV · Kathmandu</span></div><div className="mt-6 border-y-[7px] border-ink bg-ink px-4 py-7 text-center sm:px-8 sm:py-10"><p className="font-mono text-[10px] uppercase tracking-[0.4em] text-[#f5f0e7]/65">International Press Corps</p><h1 className="mt-4 font-display text-6xl font-semibold uppercase leading-[0.8] tracking-[-0.085em] text-[#f5f0e7] sm:text-8xl md:text-[9.5rem]">THE TESMUN TIMES</h1><p className="mt-5 border-t border-[#f5f0e7]/30 pt-4 font-mono text-[10px] uppercase tracking-[0.26em] text-[#f5f0e7]/65">A continuous record of debate, diplomacy and the day · {archiveArticleCount} dispatches</p></div></header><div className="mx-auto max-w-5xl">{newsArchive.map((day, dayIndex) => <section key={`${day.session}-${day.day}`} className="scroll-mt-8 pt-24 md:pt-36"><Reveal><div className="relative overflow-hidden border-y-2 border-ink py-8 md:py-12"><motion.p className="pointer-events-none absolute -right-3 top-1/2 -translate-y-1/2 font-display text-[7rem] uppercase leading-none tracking-[-0.09em] text-ink/[0.055] sm:text-[11rem] md:text-[15rem]" initial={{ x: 35 }} whileInView={{ x: 0 }} viewport={{ once: true }} transition={{ duration: 1.2 }}>{dayLabel(day.day)}</motion.p><p className="relative font-mono text-[11px] font-bold uppercase tracking-[0.28em] text-ink/55">{sessionLabel[day.session]}</p><h2 className="relative mt-3 font-display text-6xl uppercase leading-[0.82] tracking-[-0.07em] text-ink sm:text-8xl">{dayLabel(day.day)}</h2><div className="relative mt-7 h-px w-0 bg-ink/60" style={{ animation: "draw-line 1.2s cubic-bezier(.22,1,.36,1) forwards" }} /></div></Reveal><div className="pt-10 md:pt-14">{day.articles.map((article, index) => <Story key={`${day.session}-${day.day}-${article.committee}`} article={article} index={index} />)}</div>{dayIndex < newsArchive.length - 1 && <div className="mx-auto mt-8 h-16 w-px bg-ink/25" />}</section>)}</div><footer className="mt-32 border-t-2 border-ink pt-7 text-center font-mono text-[10px] uppercase tracking-[0.2em] text-ink/55">End of archive · First Session · Day 1</footer></div></main>;
}
