import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ChevronDown, X } from "lucide-react";
import { pressSections } from "@/lib/press-data";
import YouTubeEmbed from "@/components/YouTubeEmbed";
import { PersonPlaceholder } from "@/components/PersonCard";

const video = "https://www.youtube.com/watch?v=vxpm8OZRH30";
const names = ["Aarav Shrestha", "Maya Gurung", "Rohan Karki", "Saanvi Joshi", "Kabir Thapa", "Anisha Rai", "Nischal Bista", "Prakriti Lama"];
const questions = ["What brought you to TESMUN?", "What is the room teaching you?", "What makes a strong delegate?", "Which moment stays with you?", "How do you prepare?", "What should people remember?"];
const speeches = Array.from({ length: 10 }, (_, i) => ({ title: ["Opening address", "A case for listening", "Youth and responsibility", "The work behind the words", "A room worth protecting", "The diplomatic pause", "Principles into policy", "The delegate's promise", "A wider definition of leadership", "Closing reflection"][i], speaker: names[i % names.length], committee: ["Opening Ceremony", "HRC", "LP I", "UNEP", "ECOSOC"][i % 5] }));
const interviews = Array.from({ length: 20 }, (_, i) => ({ title: `Interview ${String(i + 1).padStart(2, "0")}`, subject: names[i % names.length] }));
const cartoons = Array.from({ length: 12 }, (_, i) => ({ src: `/images/cartoon-${(i % 4) + 1}.png`, alt: `TESMUN editorial cartoon ${i + 1}`, author: names[i % names.length] }));

export default function PressSection() {
  const { slug = "" } = useParams(); const section = pressSections[slug as keyof typeof pressSections]; const [team, setTeam] = useState<1 | 2>(1); const [open, setOpen] = useState(0); const [lightbox, setLightbox] = useState<number | null>(null);
  if (!section || slug === "news") return <main className="min-h-screen bg-navy-deep px-6 py-40 text-center text-warm"><h1 className="font-display text-4xl">Section not found</h1><Link to="/press" className="mt-6 inline-block text-sm uppercase tracking-[0.14em] text-gold">← Press hub</Link></main>;
  return <main className="min-h-screen bg-navy-deep px-5 pb-24 pt-28 text-warm sm:px-8 md:px-10 md:pt-40"><div className="mx-auto max-w-6xl"><Link to="/press" className="text-[11px] uppercase tracking-[0.16em] text-silver hover:text-gold">← Press hub</Link><p className="mt-12 text-[11px] uppercase tracking-[0.18em] text-gold">Press Desk</p><h1 className="font-display mt-4 text-5xl leading-[0.92] sm:text-7xl">{section.title}</h1><p className="mt-6 max-w-xl text-base leading-8 text-silver/80">{section.intro}</p>
  {slug === "interviews" && <section className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{interviews.map((item) => <article key={item.title} className="border border-white/10 bg-navy p-4"><div className="mb-4 aspect-video bg-navy-deep"><YouTubeEmbed url={video} title={item.title}/></div><p className="text-[10px] uppercase tracking-[0.16em] text-gold">Interview</p><h2 className="mt-2 font-display text-2xl">{item.title}</h2><p className="mt-2 text-sm text-silver/70">{item.subject} · video placeholder</p></article>)}</section>}
  {slug === "podcast" && <section className="mt-14 grid max-w-4xl gap-6 sm:grid-cols-2">{["Podcast episode 01", "Podcast episode 02"].map((title) => <article key={title} className="border border-white/10 bg-navy p-5"><div className="aspect-video bg-navy-deep"><YouTubeEmbed url={video} title={title}/></div><h2 className="mt-4 font-display text-3xl">{title}</h2><p className="mt-2 text-sm text-silver/70">Podcast video placeholder · link can be replaced later.</p></article>)}</section>}
  {slug === "speeches" && <section className="mt-14 max-w-4xl divide-y divide-white/15 border-y border-white/15">{speeches.map((speech, i) => <div key={speech.title}><button type="button" onClick={() => setOpen(open === i ? -1 : i)} className="flex w-full items-center justify-between gap-5 py-5 text-left"><span><span className="text-[10px] uppercase tracking-[0.16em] text-gold">{speech.committee} · {speech.speaker}</span><span className="mt-1 block font-display text-2xl sm:text-3xl">{speech.title}</span></span><ChevronDown className={`shrink-0 transition ${open === i ? "rotate-180 text-gold" : ""}`} /></button>{open === i && <div className="pb-6 text-base leading-8 text-silver/80">This speech archive placeholder will hold the delivered text, speaker attribution and committee context. The full transcript can be added here after the conference.</div>}</div>)}</section>}
  {slug === "vox-pop" && <section className="mt-14"><div className="flex gap-2 border-b border-white/15 pb-4">{[1, 2].map((n) => <button key={n} type="button" onClick={() => setTeam(n as 1 | 2)} className={`border px-4 py-2 text-[10px] uppercase tracking-[0.16em] ${team === n ? "border-gold bg-gold text-navy-deep" : "border-white/20 text-silver"}`}>Team {n}</button>)}</div><div className="mt-8 space-y-10">{questions.map((question, q) => <div key={question}><h2 className="font-display text-3xl">Q{q + 1}. {question}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{names.map((name, i) => <article key={name} className="flex items-center gap-3 border-b border-white/10 py-3"><div className="h-11 w-11 shrink-0 overflow-hidden rounded-full bg-navy"><PersonPlaceholder name={name} className="h-full w-full" /></div><div className="min-w-0"><p className="text-sm font-medium">{name}</p><p className="truncate text-xs text-silver/70">“{team === 1 ? "Listening changes the room." : "Every voice adds direction."}”</p></div></article>)}</div></div>)}</div></section>}
  {slug === "cartoons" && <section className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{cartoons.map((cartoon, i) => <button key={i} type="button" onClick={() => setLightbox(i)} className="group border border-white/10 bg-navy p-3 text-left"><img src={cartoon.src} alt={cartoon.alt} className="aspect-[4/3] w-full object-cover transition group-hover:opacity-80"/><p className="mt-3 text-[10px] uppercase tracking-[0.16em] text-gold">Cartoon {String(i + 1).padStart(2, "0")}</p><p className="mt-1 text-sm text-silver">By {cartoon.author}</p></button>)}{lightbox !== null && <div className="fixed inset-0 z-50 flex items-center justify-center bg-navy-deep/95 p-6" onClick={() => setLightbox(null)}><button type="button" aria-label="Close cartoon" className="absolute right-6 top-6"><X/></button><img src={cartoons[lightbox].src} alt={cartoons[lightbox].alt} className="max-h-[85vh] max-w-full object-contain" onClick={(e) => e.stopPropagation()}/></div>}</section>}
  {slug === "op-ed" && <section className="mt-14 grid gap-5 sm:grid-cols-2">{names.slice(0, 6).map((name) => <article key={name} className="border border-white/10 bg-navy p-6"><p className="text-[10px] uppercase tracking-[0.16em] text-gold">Contributor</p><h2 className="mt-2 font-display text-3xl">{name}</h2><p className="mt-4 text-sm text-silver/70">Opinion piece forthcoming from the TESMUN Press Desk.</p></article>)}</section>}
  </div></main>;
}
