import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ChevronDown, X } from "lucide-react";
import { pressSections, voxQuestions, opEdContributors, cartoons } from "@/lib/press-data";
import YouTubeEmbed from "@/components/YouTubeEmbed";

const video = "https://www.youtube.com/watch?v=vxpm8OZRH30";
const voxPeople = ["Aarav Shrestha", "Maya Gurung", "Rohan Karki", "Saanvi Joshi", "Kabir Thapa", "Anisha Rai", "Nischal Bista", "Prakriti Lama"];
const chairPhotos: Record<string, string> = { "TES-MP I": "/images/committees/executive-board/aakarshi.png", "TES-MP II": "/images/committees/executive-board/sakshamthapaliya.png", "TES-MP III": "/images/committees/executive-board/binayak.png", UNEP: "/images/committees/executive-board/rujal.png", DISEC: "/images/committees/executive-board/dhiki.png", ECOSOC: "/images/committees/executive-board/prateek.png", HRC: "/images/committees/executive-board/kinjal.png" };
const speechRoster = [{ speaker: "Dibas Khadka", role: "Secretary General", committee: "Opening Ceremony", photo: "/images/our-team/secgen.png" }, { speaker: "Abhash Kunwar", role: "Deputy Secretary General", committee: "Opening Ceremony", photo: "/images/our-team/abhas.png" }, ...["TES-MP I", "TES-MP II", "TES-MP III", "UNEP", "DISEC", "ECOSOC", "HRC"].map((committee) => ({ speaker: `${committee} Chair`, role: "Committee Chair", committee, photo: chairPhotos[committee] })), { speaker: "Head of IT", role: "Head of IT", committee: "Information Technology", photo: "/images/our-team/it/yubin.png" }];
const interviewSubjects = Array.from({ length: 20 }, (_, i) => ({ title: `Interview ${String(i + 1).padStart(2, "0")}`, subject: "John Doe" }));

export default function PressSection() {
  const { slug = "" } = useParams(); const section = pressSections[slug as keyof typeof pressSections]; const [open, setOpen] = useState(0); const [lightbox, setLightbox] = useState<number | null>(null);
  if (!section || slug === "news") return <main className="min-h-screen bg-navy-deep px-6 py-40 text-center text-warm"><h1 className="font-display text-4xl">Section not found</h1><Link to="/press" className="mt-6 inline-block text-sm uppercase tracking-[0.14em] text-gold">← Press hub</Link></main>;
  return <main className="min-h-screen bg-[linear-gradient(135deg,#071a33,#123b72)] px-5 pb-24 pt-28 text-warm sm:px-8 md:px-10 md:pt-40"><div className="mx-auto max-w-6xl"><Link to="/press" className="text-[11px] uppercase tracking-[0.16em] text-silver hover:text-gold">← Press hub</Link><p className="mt-12 text-[11px] uppercase tracking-[0.18em] text-gold">Press Desk</p><h1 className="font-display mt-4 text-5xl leading-[0.92] sm:text-7xl">{section.title}</h1><p className="mt-6 max-w-xl text-base leading-8 text-silver/80">{section.intro}</p>
  {slug === "interviews" && <section className="mt-14 grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{interviewSubjects.map((item) => <article key={item.title} className="border border-white/10 bg-navy p-5 shadow-2xl"><div className="mb-5 aspect-video bg-navy-deep"><YouTubeEmbed url={video} title={item.title}/></div><p className="text-[10px] uppercase tracking-[0.16em] text-gold">Interview</p><h2 className="mt-2 font-display text-2xl">{item.title}</h2><p className="mt-2 text-sm text-silver/70">{item.subject} · video placeholder</p></article>)}</section>}
  {slug === "podcast" && <section className="mt-14 grid max-w-4xl gap-6 sm:grid-cols-2">{["Podcast episode 01", "Podcast episode 02"].map((title) => <article key={title} className="border border-white/10 bg-navy p-5"><div className="aspect-video bg-navy-deep"><YouTubeEmbed url={video} title={title}/></div><h2 className="mt-4 font-display text-3xl">{title}</h2></article>)}</section>}
  {slug === "speeches" && <section className="mt-14 max-w-5xl divide-y divide-white/15 border-y border-white/15">{speechRoster.map((speech, i) => <div key={speech.speaker}><button type="button" onClick={() => setOpen(open === i ? -1 : i)} className="flex w-full items-center justify-between gap-5 py-8 text-left"><span className="flex items-center gap-6"><img src={speech.photo} alt={`${speech.speaker} portrait`} className="h-24 w-24 shrink-0 rounded-full border border-gold/30 object-cover sm:h-32 sm:w-32" /><span><span className="text-[10px] uppercase tracking-[0.16em] text-gold">{speech.committee} · {speech.role}</span><span className="mt-2 block font-display text-3xl sm:text-4xl">{speech.speaker}</span></span></span><ChevronDown className={`shrink-0 transition ${open === i ? "rotate-180 text-gold" : ""}`} /></button>{open === i && <div className="pb-8 pl-0 text-base leading-8 text-silver/80 sm:pl-36">Speech text will be added to this archive after the conference record is supplied.</div>}</div>)}</section>}
  {slug === "vox-pop" && <section className="mt-14 space-y-12">{voxQuestions.map((item, q) => <div key={item.question} className="border-t border-gold/30 pt-8"><h2 className="font-display text-3xl sm:text-4xl">Q{q + 1}. {item.question}</h2><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{voxPeople.map((name, i) => <article key={`${name}-${q}`} className="border border-white/10 bg-navy p-5 shadow-2xl"><img src="/images/our-team/press/interview-portrait.jpg" alt={`${name} portrait placeholder`} className="mx-auto h-32 w-32 rounded-full border border-gold/30 object-cover" /><p className="mt-5 text-lg font-medium">{name}</p><p className="mt-2 text-sm leading-6 text-silver/70">“{item.answers[i % item.answers.length]}”</p></article>)}</div></div>)}</section>}
  {slug === "cartoons" && <section className="mt-14 grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{cartoons.map((cartoon, i) => <button key={i} type="button" onClick={() => setLightbox(i)} className="group border border-white/10 bg-navy p-4 text-left shadow-2xl"><img src={cartoon.src} alt={cartoon.alt} className="aspect-[4/3] w-full object-cover transition group-hover:opacity-80"/><p className="mt-4 text-[10px] uppercase tracking-[0.16em] text-gold">Cartoon {String(i + 1).padStart(2, "0")}</p><p className="mt-2 text-sm text-silver">By John Doe</p></button>)}{lightbox !== null && <div className="fixed inset-0 z-50 flex items-center justify-center bg-navy-deep/95 p-6" onClick={() => setLightbox(null)}><button type="button" aria-label="Close cartoon" className="absolute right-6 top-6"><X/></button><img src={cartoons[lightbox].src} alt={cartoons[lightbox].alt} className="max-h-[85vh] max-w-full object-contain" onClick={(e) => e.stopPropagation()}/></div>}</section>}
  {slug === "op-ed" && <section className="mt-14 grid gap-8 sm:grid-cols-2">{opEdContributors.map((contributor, index) => <a key={`${contributor.name}-${index}`} href={contributor.pdf || "https://drive.google.com/"} target="_blank" rel="noreferrer" className="group border-y border-white/15 py-10 transition-colors hover:border-gold/70"><div className="flex items-center gap-6"><img src={contributor.photo || "/images/our-team/press/interview-portrait.jpg"} alt={`${contributor.name} portrait`} className="h-48 w-48 shrink-0 rounded-full border border-gold/30 object-cover"/><div><p className="text-[10px] uppercase tracking-[0.16em] text-gold">Contributor · Read PDF</p><h2 className="mt-2 font-display text-4xl group-hover:text-gold">{contributor.name}</h2><p className="mt-2 text-sm text-silver/70">{contributor.role}</p></div></div></a>)}</section>}
  </div></main>;
}

